#[cfg(test)]
pub mod utils;

#[cfg(test)]
mod unit {
    pub mod llm_provider_test;
    pub mod evaluation_test;
    pub mod prompt_formatter_test;
    pub mod context_formatter_test;
    pub mod context_integrator_test;
    pub mod token_counter_test;
    pub mod context_window_manager_test;
    pub mod cost_calculator_test;
    pub mod budget_manager_test;
    pub mod provider_token_counter_test;
    pub mod model_registry_test;
    pub mod model_health_checker_test;
    pub mod efficiency_score_test;
    pub mod model_selector_test;
    pub mod load_balancer_test;
    pub mod fallback_manager_test;
    pub mod fallback_notification_test;
    pub mod budget_reset_listener_test;
    pub mod cache_manager_test;
    pub mod cache_invalidator_test;
    pub mod streaming_manager_test;
    pub mod video_stream_processor_test;
    pub mod request_queue_manager_test;
    pub mod priority_queue_manager_test;
    pub mod secure_key_storage_test;
    pub mod key_rotation_manager_test;
    pub mod metrics_collector_test;
    pub mod model_performance_tracker_test;
    pub mod provider_error_handler_test;
    pub mod retry_manager_test;
    pub mod context_logger_test;
    pub mod vision_provider_test;
    pub mod openai_client_test;
    pub mod openai_llm_provider_test;
    pub mod anthropic_client_test;
    pub mod anthropic_llm_provider_test;
    pub mod grpc_model_registry_test;
    pub mod google_client_test;
    pub mod google_llm_provider_test;
    pub mod llamacpp_client_test;
    pub mod llamacpp_llm_provider_test;
    pub mod bitnet_client_test;
    pub mod bitnet_llm_provider_test;
    pub mod local_manager_test;
    pub mod model_downloader_test;
    pub mod performance_tracker_test;
    pub mod engine_test;
}
